import { Meta } from "@storybook/react";

import { ListAtomItems } from "../../../atoms/list-atom";
import { ListItemProps } from "../List";

const ListItem = <Fields extends ListAtomItems>(
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  props: ListItemProps<Fields>,
) => <></>;

const meta = {
  component: ListItem,
  // TODO: drop the custom argTypes, as it should be autogenerated from the component property!
  argTypes: {
    item: {
      description:
        "Current list item. Can be used as argument to `add`, `move` or `remove`.",
      table: {
        type: {
          summary: "ListItem<Fields>",
        },
      },
    },
    index: {
      description: "Index of the current item",
      table: {
        type: {
          summary: "number",
        },
      },
    },
    count: {
      description: "Total count of items",
      table: {
        type: {
          summary: "number",
        },
      },
    },
    add: {
      description:
        "Append a new item to the end of the list. WHen called with current item, it will be prepend with a new item.",
      table: {
        type: {
          summary: "(before?: ListItem<Fields>) => void",
        },
      },
    },
    remove: {
      description: "Removes the current item.",
      table: {
        type: {
          summary: "() => void",
        },
      },
    },
    moveUp: {
      description:
        "Moves the current item one slot up in the list. When called for the first item, the action is no-op.",
      table: {
        type: {
          summary: "() => void",
        },
      },
    },
    moveDown: {
      description:
        "Moves the current item one slot down in the list. When called for the last item, the item moves to the start of the list.",
      table: {
        type: {
          summary: "() => void",
        },
      },
    },
    RemoveButton: {
      description:
        "A component to render the `RemoveButton` passed to the original `<ListField />`. It removes the current item when clicked.. It doesn't accept props.",
      table: {
        type: {
          summary: "FunctionComponent",
        },
      },
    },
  },
} satisfies Meta<typeof ListItem>;

export default meta;

export const Primary = {};
